name: Coverage check

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Running coverage tests
        run: yarn coverage
        env:
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
      - name: Upload coverage report
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
